### PR TITLE
Update networking from to v1, update k8s.io libs to v020.6

### LINKED ISSUE #34: Kubernetes config for k8s doesn't use helm
The port, host and a few other values are hard coded for k8s configs at ./build/k8s
@ptcar2009 I'm not sure if this file is used, but if it is should we consider move it to a helm chart?

### PR DESCRIPTION
**Pull request by brenordr**
# Description

The extensions/v1beta1 and networking.k8s.io/v1beta1 API versions of Ingress was deprecated and will no longer be served in v1.22. This PR apply the requested fixes, described at:

https://kubernetes.io/docs/reference/using-api/deprecation-guide/

Notable changes:
- spec.backend is renamed to spec.defaultBackend
- The backend serviceName field is renamed to service.name
- Numeric backend servicePort fields are renamed to service.port.number
- String backend servicePort fields are renamed to service.port.name
- pathType is now required for each specified path. Options are Prefix, Exact, and ImplementationSpecific. To match the undefined v1beta1 behavior, use ImplementationSpecific.

We also use use an older version of k8s.io libraries, this PR updates to v20.6

Kind: Upgrade
Section: Helm
Summary: -
Issue link: -

## Changelog

> Helm charts for insprd, auth and ui provider

## Pay attention to
Check if the ingress works as expected, I've run the tests locally and seems to be all fine.

> Important parts of the code that require special attention

Ingress now has two options for port, numeric and string
looking our config I've choose to use numeric, but it can be an issue if we support string defined ports

### CODE REVIEW

**Comment by ptcar2009** [comment]
We are currently working under the 16.8 version of kubernetes, that is considered stable and lts. We can look into rolling out with the current version, but I really do think we should have branches for it.

**Comment by brenordr** [comment]
will be good establish a process for it, currently v1.20.6 is the latest version. I understand v1.16.8 is the stable and stablished.
We need to know how it affect the usage in newer clusters, and how to maintain. Ideally we should keep up with the cloud providers most common versions of kubernetes

**Comment by brenordr** [comment]
@ptcar2009 One proposal I have is to support one version as LTS and other version as most recent, most of the APIs are the same. We can use something like https://www.percona.com/blog/2020/03/09/using-different-versions-of-a-package-in-an-application-via-go-modules/ for insprd

Regards the helm itself, I don't know if we can add something like a flag that checks for version and select the correct version?

**Comment by brenordr** [comment]
Just checked, we don't actually use ingress yet into the project, so the only place we need to check for incompatibilities is the helm. I like the branching idea, but we need to do more regards the releases.

**Comment by brenordr** [comment]
@inspr/core This seems actually good to go. Doesn't create any breaking change. I would like to request a deeper review though and this PR doesn't have priority

**Review by luiz-couto — APPROVED** [review]

**Review by nicholaspcr — COMMENTED** [review]
From what i have read in the in the site that you gave in previous comments, there is a question in regards to the `pathtype` variable in the yamls.

pathType is now required for each specified path. Options are Prefix, Exact, and ImplementationSpecific. To match the undefined v1beta1 behavior, use ImplementationSpecific.

Wouldn't `ImplementationSpecific` would fit better than `Prefix`?

**Comment by brenordr** [comment]
@nicholaspcr Yes, but I believe the behavior we want is actually the Prefix all along

**Comment by brenordr** [comment]
@ptcar2009 Thoughts?

**Comment by ptcar2009** [comment]
I think that exact would maybe be better actually, because we don't want to overshadow any routes, and doing by prefix we overshadow them

**Comment by brenordr** [comment]
@ptcar2009 I don't think so. In fact those routes should be dedicated to insprd.
`/app/mydapp` for example

People using inspr will need to expose a subdomain, to use https reliably, using it with a site for example can be quite problematic.

We can allow such behavior but we will need to handle traffic at L7 before forward to the services in the cluster.

**Review by franciscobonand — APPROVED** [review]

**Review by nicholaspcr — APPROVED** [review]
Since it seems that both @brenordr and @ptcar2009 talked about the `pathType` commentary that i made earlier i opted for approaving this PR.

**Comment by brenordr** [comment]
@inspr/core I think now it's good to go. Just tested locally and seems all good

**Comment by brenordr** [comment]
@inspr/core Guys we will merge this?

**Comment by franciscobonand** [comment]
@brenordr We were planning to ask you about both of your PRs that are open, actually. Should this be merged?

**Review by franciscobonand — APPROVED** [review]
As long as a manual integration test was made, LGTM!

**Review by LucasStarlingdePaulaSalles — APPROVED** [review]

**Review by luiz-couto — APPROVED** [review]

**Pull request merged**
